/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author aghsk
 */
public class PanelColores extends javax.swing.JPanel {

    public Color colorSeleccionado = Color.RED;

    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rojo = new javax.swing.JLabel();
        Azul = new javax.swing.JLabel();
        Negro = new javax.swing.JLabel();
        Amarillo = new javax.swing.JLabel();
        Blanco = new javax.swing.JLabel();
        Verde = new javax.swing.JLabel();
        Rosa = new javax.swing.JLabel();
        Naranja = new javax.swing.JLabel();
        Azul1 = new javax.swing.JLabel();
        Rojo1 = new javax.swing.JLabel();
        Negro1 = new javax.swing.JLabel();
        Amarillo1 = new javax.swing.JLabel();
        Blanco1 = new javax.swing.JLabel();
        Verde1 = new javax.swing.JLabel();
        Rosa1 = new javax.swing.JLabel();
        Naranja1 = new javax.swing.JLabel();
        Azul2 = new javax.swing.JLabel();
        Rojo2 = new javax.swing.JLabel();
        Negro2 = new javax.swing.JLabel();
        Amarillo2 = new javax.swing.JLabel();
        Blanco2 = new javax.swing.JLabel();
        Verde2 = new javax.swing.JLabel();
        Rosa2 = new javax.swing.JLabel();
        Naranja2 = new javax.swing.JLabel();
        Azul3 = new javax.swing.JLabel();
        Rojo3 = new javax.swing.JLabel();
        Negro3 = new javax.swing.JLabel();
        Amarillo3 = new javax.swing.JLabel();
        Blanco3 = new javax.swing.JLabel();
        Verde3 = new javax.swing.JLabel();
        Rosa3 = new javax.swing.JLabel();
        Naranja3 = new javax.swing.JLabel();

        Rojo.setBackground(new java.awt.Color(255, 51, 51));
        Rojo.setOpaque(true);
        Rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RojoMousePressed(evt);
            }
        });

        Azul.setBackground(new java.awt.Color(51, 51, 255));
        Azul.setOpaque(true);
        Azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AzulMousePressed(evt);
            }
        });

        Negro.setBackground(new java.awt.Color(0, 0, 0));
        Negro.setOpaque(true);
        Negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NegroMousePressed(evt);
            }
        });

        Amarillo.setBackground(new java.awt.Color(255, 255, 0));
        Amarillo.setOpaque(true);
        Amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AmarilloMousePressed(evt);
            }
        });

        Blanco.setBackground(new java.awt.Color(255, 255, 255));
        Blanco.setOpaque(true);
        Blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BlancoMousePressed(evt);
            }
        });

        Verde.setBackground(new java.awt.Color(51, 204, 0));
        Verde.setOpaque(true);
        Verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerdeMousePressed(evt);
            }
        });

        Rosa.setBackground(new java.awt.Color(255, 0, 204));
        Rosa.setOpaque(true);
        Rosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RosaMousePressed(evt);
            }
        });

        Naranja.setBackground(new java.awt.Color(255, 153, 51));
        Naranja.setOpaque(true);
        Naranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NaranjaMousePressed(evt);
            }
        });

        Azul1.setBackground(new java.awt.Color(153, 153, 153));
        Azul1.setOpaque(true);
        Azul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Azul1MousePressed(evt);
            }
        });

        Rojo1.setBackground(new java.awt.Color(0, 255, 255));
        Rojo1.setOpaque(true);
        Rojo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rojo1MousePressed(evt);
            }
        });

        Negro1.setBackground(new java.awt.Color(0, 51, 153));
        Negro1.setOpaque(true);
        Negro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Negro1MousePressed(evt);
            }
        });

        Amarillo1.setBackground(new java.awt.Color(0, 153, 204));
        Amarillo1.setOpaque(true);
        Amarillo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Amarillo1MousePressed(evt);
            }
        });

        Blanco1.setBackground(new java.awt.Color(153, 0, 102));
        Blanco1.setOpaque(true);
        Blanco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Blanco1MousePressed(evt);
            }
        });

        Verde1.setBackground(new java.awt.Color(102, 0, 153));
        Verde1.setOpaque(true);
        Verde1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Verde1MousePressed(evt);
            }
        });

        Rosa1.setBackground(new java.awt.Color(153, 153, 0));
        Rosa1.setOpaque(true);
        Rosa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rosa1MousePressed(evt);
            }
        });

        Naranja1.setBackground(new java.awt.Color(153, 0, 0));
        Naranja1.setOpaque(true);
        Naranja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Naranja1MousePressed(evt);
            }
        });

        Azul2.setBackground(new java.awt.Color(0, 153, 102));
        Azul2.setOpaque(true);
        Azul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Azul2MousePressed(evt);
            }
        });

        Rojo2.setBackground(new java.awt.Color(0, 51, 0));
        Rojo2.setOpaque(true);
        Rojo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rojo2MousePressed(evt);
            }
        });

        Negro2.setBackground(new java.awt.Color(204, 102, 255));
        Negro2.setOpaque(true);
        Negro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Negro2MousePressed(evt);
            }
        });

        Amarillo2.setBackground(new java.awt.Color(153, 102, 255));
        Amarillo2.setOpaque(true);
        Amarillo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Amarillo2MousePressed(evt);
            }
        });

        Blanco2.setBackground(new java.awt.Color(0, 204, 51));
        Blanco2.setOpaque(true);
        Blanco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Blanco2MousePressed(evt);
            }
        });

        Verde2.setBackground(new java.awt.Color(51, 0, 0));
        Verde2.setOpaque(true);
        Verde2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Verde2MousePressed(evt);
            }
        });

        Rosa2.setBackground(new java.awt.Color(102, 255, 204));
        Rosa2.setOpaque(true);
        Rosa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rosa2MousePressed(evt);
            }
        });

        Naranja2.setBackground(new java.awt.Color(255, 102, 102));
        Naranja2.setOpaque(true);
        Naranja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Naranja2MousePressed(evt);
            }
        });

        Azul3.setBackground(new java.awt.Color(51, 102, 255));
        Azul3.setOpaque(true);
        Azul3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Azul3MousePressed(evt);
            }
        });

        Rojo3.setBackground(new java.awt.Color(51, 51, 51));
        Rojo3.setOpaque(true);
        Rojo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rojo3MousePressed(evt);
            }
        });

        Negro3.setBackground(new java.awt.Color(255, 153, 153));
        Negro3.setOpaque(true);
        Negro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Negro3MousePressed(evt);
            }
        });

        Amarillo3.setBackground(new java.awt.Color(204, 204, 0));
        Amarillo3.setOpaque(true);
        Amarillo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Amarillo3MousePressed(evt);
            }
        });

        Blanco3.setBackground(new java.awt.Color(0, 204, 153));
        Blanco3.setOpaque(true);
        Blanco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Blanco3MousePressed(evt);
            }
        });

        Verde3.setBackground(new java.awt.Color(153, 255, 0));
        Verde3.setOpaque(true);
        Verde3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Verde3MousePressed(evt);
            }
        });

        Rosa3.setBackground(new java.awt.Color(102, 102, 0));
        Rosa3.setOpaque(true);
        Rosa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Rosa3MousePressed(evt);
            }
        });

        Naranja3.setBackground(new java.awt.Color(255, 51, 51));
        Naranja3.setOpaque(true);
        Naranja3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Naranja3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Negro2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Verde2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blanco2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Naranja2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rosa2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Negro3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Verde3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blanco3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Naranja3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rosa3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Negro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Negro1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Verde1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blanco1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Naranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rosa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Rosa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blanco1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Negro1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Azul1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Negro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Azul, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Rosa2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naranja2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blanco2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Negro2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amarillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Azul2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rosa3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naranja3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blanco3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Negro3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amarillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Azul3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RojoMousePressed
        // Rojo
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();


    }//GEN-LAST:event_RojoMousePressed

    private void AzulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AzulMousePressed
        // Azul
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_AzulMousePressed

    private void NegroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NegroMousePressed
        // Negro
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
    }//GEN-LAST:event_NegroMousePressed

    private void AmarilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmarilloMousePressed
        // Amarillo
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_AmarilloMousePressed

    private void BlancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlancoMousePressed
        // Blanco
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_BlancoMousePressed

    private void VerdeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerdeMousePressed
        // Verde
        colorSeleccionado = Color.GREEN;
    }//GEN-LAST:event_VerdeMousePressed

    private void RosaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RosaMousePressed
        // Rosa
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_RosaMousePressed

    private void NaranjaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NaranjaMousePressed
        // Naranja
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_NaranjaMousePressed

    private void Azul1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Azul1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Azul1MousePressed

    private void Rojo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rojo1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rojo1MousePressed

    private void Negro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Negro1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Negro1MousePressed

    private void Amarillo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amarillo1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Amarillo1MousePressed

    private void Blanco1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blanco1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Blanco1MousePressed

    private void Verde1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verde1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Verde1MousePressed

    private void Rosa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rosa1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rosa1MousePressed

    private void Naranja1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Naranja1MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Naranja1MousePressed

    private void Azul2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Azul2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Azul2MousePressed

    private void Rojo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rojo2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rojo2MousePressed

    private void Negro2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Negro2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Negro2MousePressed

    private void Amarillo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amarillo2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Amarillo2MousePressed

    private void Blanco2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blanco2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Blanco2MousePressed

    private void Verde2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verde2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Verde2MousePressed

    private void Rosa2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rosa2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rosa2MousePressed

    private void Naranja2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Naranja2MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Naranja2MousePressed

    private void Azul3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Azul3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Azul3MousePressed

    private void Rojo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rojo3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rojo3MousePressed

    private void Negro3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Negro3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Negro3MousePressed

    private void Amarillo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amarillo3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Amarillo3MousePressed

    private void Blanco3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blanco3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Blanco3MousePressed

    private void Verde3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verde3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Verde3MousePressed

    private void Rosa3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rosa3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Rosa3MousePressed

    private void Naranja3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Naranja3MousePressed
        // TODO add your handling code here:
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();

    }//GEN-LAST:event_Naranja3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amarillo;
    private javax.swing.JLabel Amarillo1;
    private javax.swing.JLabel Amarillo2;
    private javax.swing.JLabel Amarillo3;
    private javax.swing.JLabel Azul;
    private javax.swing.JLabel Azul1;
    private javax.swing.JLabel Azul2;
    private javax.swing.JLabel Azul3;
    private javax.swing.JLabel Blanco;
    private javax.swing.JLabel Blanco1;
    private javax.swing.JLabel Blanco2;
    private javax.swing.JLabel Blanco3;
    private javax.swing.JLabel Naranja;
    private javax.swing.JLabel Naranja1;
    private javax.swing.JLabel Naranja2;
    private javax.swing.JLabel Naranja3;
    private javax.swing.JLabel Negro;
    private javax.swing.JLabel Negro1;
    private javax.swing.JLabel Negro2;
    private javax.swing.JLabel Negro3;
    private javax.swing.JLabel Rojo;
    private javax.swing.JLabel Rojo1;
    private javax.swing.JLabel Rojo2;
    private javax.swing.JLabel Rojo3;
    private javax.swing.JLabel Rosa;
    private javax.swing.JLabel Rosa1;
    private javax.swing.JLabel Rosa2;
    private javax.swing.JLabel Rosa3;
    private javax.swing.JLabel Verde;
    private javax.swing.JLabel Verde1;
    private javax.swing.JLabel Verde2;
    private javax.swing.JLabel Verde3;
    // End of variables declaration//GEN-END:variables

}
